version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: github.com/charmbracelet/lipgloss/v2
        versions:
          - v2.0.0-beta1
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/www"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker:
        patterns:
          - "*"

  # Docs:
  - package-ecosystem: "pip"
    directory: "/www"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "05:00"
      timezone: "America/Sao_Paulo"
    labels:
      - "dependencies"
    commit-message:
      prefix: "docs"
      include: "scope"
    groups:
      docs:
        patterns:
          - "*"
