name: docs

on:
  push:
    branches:
      - "main"
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"
      - flake.nix
      - flake.lock
  pull_request:
    paths:
      - "www/**/*"
      - ".github/workflows/docs.yml"
      - flake.nix
      - flake.lock

permissions:
  contents: read

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task docs:test
