name: "security"

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 2 * * *"

concurrency:
  group: codeql-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  openssf:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read
      issues: read
      pull-requests: read
      checks: read
    steps:
      - uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde
  codeql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["go", "actions"]
    permissions:
      actions: read
      contents: read
      pull-requests: read
      security-events: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          persist-credentials: false
      - uses: github/codeql-action/init@192325c86100d080feab897ff886c34abd4c83a3 # v3
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@192325c86100d080feab897ff886c34abd4c83a3 # v3
      - uses: github/codeql-action/analyze@192325c86100d080feab897ff886c34abd4c83a3 # v3
